#!/bin/bash

# Jerry Mak, Dan Lawrence
#
# Script to simulate 1 week of Quibble. Runs the daily script 5 times with pre defined inputs
# from a specified input folder. Expects to find tests in the form of input-X-terminal-Y, where
# X is the input for the specific day in the week and Y is the session number of that day.
#
# Usage: weekly
#
# Exits with:
#
#     0 - if the simulation runs successfully without crashing
#     1 - if either the backend or frontend crash during the simulation
#     2 - if the script is run with incorrect parameters

if [[ $# -ne 1 || ! -d $1 ]]; then
    echo "Usage: weekly input_dir" >&2
    exit 2
fi

i=1
while (( i < 6 )); do
    "$(dirname $0)/daily" $1/input-$i-terminal-*

    if [[ $? -ne 0 ]]; then
        exit 1
    fi

    (( i++ ))
done
